---
name: Action Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-check
