---
name: Action Lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
    paths:
      - '.github/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-check
