---
name: e2e SDK tests

on:
  workflow_dispatch:
    secrets:
      INFURA_PROJECT_ID:
        required: true
      INFURA_PROJECT_SECRET:
        required: true
      WALLET_PUBLIC_ADDRESS:
        required: true
      WALLET_PRIVATE_KEY:
        required: true
      EVM_RPC_URL:
        required: true
      INFURA_IPFS_PROJECT_ID:
        required: true
      INFURA_IPFS_PROJECT_SECRET:
        required: true
      INFURA_IPFS_ENDPOINT:
        required: true
      INFURA_IPFS_GATEWAY:
        required: true
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - v18.1.0

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install packages
        run: npm ci

      - name: Run e2e tests
        run: npm run test:e2e
        env:
          WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
          INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
          INFURA_PROJECT_SECRET: ${{ secrets.INFURA_PROJECT_SECRET }}
          EVM_RPC_URL: ${{ secrets.EVM_RPC_URL }}
          WALLET_PUBLIC_ADDRESS: ${{ secrets.WALLET_PUBLIC_ADDRESS }}
          INFURA_IPFS_PROJECT_ID: ${{ secrets.INFURA_IPFS_PROJECT_ID }}
          INFURA_IPFS_PROJECT_SECRET: ${{ secrets.INFURA_IPFS_PROJECT_SECRET }}
          INFURA_IPFS_GATEWAY: ${{ secrets.INFURA_IPFS_GATEWAY }}
          INFURA_IPFS_ENDPOINT: ${{ secrets.INFURA_IPFS_ENDPOINT }}
