---
name: Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - v18.1.0
          - v16.13.1

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install packages
        run: npm ci

      - name: Run integration tests
        run: npm run test:integration
        env:
          WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
          INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
          INFURA_PROJECT_SECRET: ${{ secrets.INFURA_PROJECT_SECRET }}
          EVM_RPC_URL: ${{ secrets.EVM_RPC_URL }}
          WALLET_PUBLIC_ADDRESS: ${{ secrets.WALLET_PUBLIC_ADDRESS }}
          INFURA_IPFS_PROJECT_ID: ${{ secrets.INFURA_IPFS_PROJECT_ID }}
          INFURA_IPFS_PROJECT_SECRET: ${{ secrets.INFURA_IPFS_PROJECT_SECRET }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@25b0be1ad1c39388799624b0d0914282bc36ac8e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: v18.1.0
          cache: npm

      - name: Install packages
        run: npm ci

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: 'public'
      #    token: ${{ secrets.PRIVATE_REGISTRY_TOKEN }}
      #    registry: https://registry.nft.consensys-solutions.net

      # uncomment to publish publicly
      # - name: Publish on NPM
      #   run: |
      #     echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
      #     npm publish --registry https://registry.npmjs.org/
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # bump version manually (e.g., before creating the tag)
      # - name: Setup git info
      #   run: |
      #     git config --global user.email "johannbich@gmail.com"
      #     git config --global user.name "kalote"

      # - name: Bump npm version
      #   run: npm version ${{ github.ref_name }} -m "bump version to %s"

      # - name: Commit version
      #   run: |
      #     git status
      #     git push
