---
name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - v18.1.0
          - v16.13.1

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install packages
        run: npm ci

      - name: Run unit tests
        run: npm run test
        env:
          RPC_URL: ${{ secrets.RPC_URL }}

      - name: Run e2e tests
        run: npm run test:e2e
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          SECRET_ID: ${{ secrets.SECRET_ID }}
          RPC_URL: ${{ secrets.RPC_URL }}
