---
name: Verification

on: [pull-request]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: v18.1.0
          cache: npm
      
      - name: verification of commit message
        run: echo "verification"